/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import javax.swing.JOptionPane;

import dao.GuestDAO;
import dao.RoomBookingDAO;
import dao.RoomGuestDAO;
import dao.RoomDAO;
import dao.PersonDAO;
import dao.InvoiceDAO;

import model.Person;
import model.Room;
import model.RoomBooking;
import model.Guest;
import model.Invoice;
import types.BookingStatus;
import types.RoomStatus;
import types.PaymentStatus;

import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.ArrayList;

/**
 *
 * @author Thang
 */
public class CheckIn extends javax.swing.JFrame {

    private String userID;

    public CheckIn() {
        setTitle("Check In");
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        initComponents();
        loadRoomBookingTable("Only Confirmed");
        loadCheckInTimeFld();
    }

    public CheckIn(String userID) {
        this.userID = userID;
        System.out.println("Check In: " + userID);

        setTitle("Check In");
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        initComponents();
        loadRoomBookingTable("Only Confirmed");
        loadCheckInTimeFld();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guestCheckInFld = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        checkInTimeFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        checkInButton = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        guestNameFld = new javax.swing.JTextField();
        UsernameTxt = new javax.swing.JLabel();
        UsernameTxt1 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        UsernameTxt2 = new javax.swing.JLabel();
        roomTypeFld = new javax.swing.JTextField();
        UsernameTxt3 = new javax.swing.JLabel();
        bedsFld = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(215, 210, 203));
        jLabel.setText("Guest Check In");

        checkInTimeFld.setDisabledTextColor(java.awt.Color.black);
        checkInTimeFld.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(215, 210, 203));
        jLabel1.setText("Time CheckIn");

        checkInButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkInButton.setText("CheckIn");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        guestNameFld.setDisabledTextColor(java.awt.Color.black);
        guestNameFld.setEnabled(false);

        UsernameTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt.setText("Guest Name");

        UsernameTxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt1.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt1.setText("Phone");

        phoneField.setDisabledTextColor(java.awt.Color.black);
        phoneField.setEnabled(false);

        UsernameTxt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt2.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt2.setText("Room Type");

        roomTypeFld.setDisabledTextColor(java.awt.Color.black);
        roomTypeFld.setEnabled(false);

        UsernameTxt3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt3.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt3.setText("Bed(s)");

        bedsFld.setDisabledTextColor(java.awt.Color.black);
        bedsFld.setEnabled(false);

        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(checkInTimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(checkInButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel)
                                    .addComponent(UsernameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(roomTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(UsernameTxt)
                            .addGap(29, 29, 29)
                            .addComponent(guestNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(UsernameTxt2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guestCheckInFld, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedsFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestCheckInFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkInTimeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedsFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(checkInButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadRoomBookingTable(String choice){
        RoomBookingDAO roomBookingDAO = new RoomBookingDAO();
        jTable2.setModel(roomBookingDAO.getRoomBooking(choice));
    }

    private void loadCheckInTimeFld(){
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
        checkInTimeFld.setText(sdf.format(date));
    }

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        // TODO add your handling code here:
        loadCheckInTimeFld();
        String guestName = guestCheckInFld.getText();

        int row = jTable2.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a room to check in");
            return;
        }

        if (guestName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the guest name");
            return;
        }

        // CheckInTime must be after StartDate
        String checkInTime = checkInTimeFld.getText();
        String checkInTimeFromTable = jTable2.getValueAt(row, 2).toString();
        if (checkInTime.compareTo(checkInTimeFromTable) < 0) {
            JOptionPane.showMessageDialog(null, "CheckIn time must be after " + checkInTimeFromTable);
            return;
        }

        int bookingID = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
        Date checkInDate = new Date();
        int roomNumber = Integer.parseInt(jTable2.getValueAt(row, 1).toString());

        RoomBooking roomBooking = new RoomBookingDAO().getRoomBookingByBookingID(bookingID);
        roomBooking.setCheckIn(checkInDate);
        roomBooking.setBookingStatus(BookingStatus.CHECKED_IN);


        Room room = new RoomDAO().getRoomByRoomNumber(roomNumber);
        room.setRoomStatus(RoomStatus.OCCUPIED);
        if (room.getGuestName() == null) {
            room.setGuestName(new ArrayList<>());
        }
        room.getGuestName().add(guestName);

        Guest guest = new GuestDAO().getGuestByID(roomBooking.getGuestID());
        guest.setID(roomBooking.getGuestID());
        guest.setTotalRoomCheckedIn(guest.getTotalRoomCheckedIn() + 1);        


        long diffInMillies = Math.abs(roomBooking.getEndDate().getTime() - roomBooking.getStartDate().getTime());
        long diffInDays = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);

        Invoice invoice = new Invoice();
        invoice.setBookingID(bookingID);
        invoice.setTotalAmount(room.getBookingPrice() * diffInDays);
        invoice.setPaymentStatus(PaymentStatus.UNPAID);

        try {
            new RoomBookingDAO().updateBookingStatus(bookingID, roomBooking);
            new RoomGuestDAO().insertRoomGuest(room);
            new RoomDAO().updateRoom(room);
            new GuestDAO().updateGuest(guest);
            new InvoiceDAO().createInvoice(invoice);

            JOptionPane.showMessageDialog(null, "Check In successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Check In failed");
            e.printStackTrace();
        }
        loadRoomBookingTable("Only Confirmed");
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        // if userID starts with "G" then back to DashboardGuest, with "R" then back to DashboardReceptionist, with "M" then back to DashboardManager
        if (userID.startsWith("G")) {
            new DashboardGuest(userID).setVisible(true);
        } else if (userID.startsWith("R")) {
            try {
                new DashboardReceptionist(userID).setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (userID.startsWith("M")) {
            try {
                new DashboardManager(userID).setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
        loadCheckInTimeFld();
 
        int row = jTable2.getSelectedRow();
        String guestID = jTable2.getValueAt(row, 7).toString();

        Person person = new PersonDAO().getPersonByID(guestID);
        guestNameFld.setText(person.getName());
        phoneField.setText(person.getPhone());       

        Room room = new RoomDAO().getRoomByRoomNumber(Integer.parseInt(jTable2.getValueAt(row, 1).toString()));
        roomTypeFld.setText(room.getStyle().toString());
        bedsFld.setText(String.valueOf(room.getNumBeds()));
    }//GEN-LAST:event_jTable2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsernameTxt;
    private javax.swing.JLabel UsernameTxt1;
    private javax.swing.JLabel UsernameTxt2;
    private javax.swing.JLabel UsernameTxt3;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bedsFld;
    private javax.swing.JToggleButton checkInButton;
    private javax.swing.JTextField checkInTimeFld;
    private javax.swing.JTextField guestCheckInFld;
    private javax.swing.JTextField guestNameFld;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField roomTypeFld;
    // End of variables declaration//GEN-END:variables
}
