/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.JOptionPane;

import dao.InvoiceDAO;
import dao.PersonDAO;
import dao.RoomBookingDAO;
import dao.ServiceDAO;
import dto.Invoice;
import dto.Person;
import dto.Service;
import types.ServiceStatus;

/**
 *
 * @author Thang
 */
public class ConfirmService extends javax.swing.JFrame {

    private String userID;

    public ConfirmService() {
        setTitle("Confirm Service");
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        initComponents();
        loadServiceTable("Only Requested");
    }

    public ConfirmService(String userID) {
        this.userID = userID;
        System.out.println("Confirm Service: " + userID);

        setTitle("Confirm Service");
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        initComponents();
        loadServiceTable("Only Requested");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        UsernameTxt2 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        UsernameTxt1 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JToggleButton();
        UsernameTxt = new javax.swing.JLabel();
        cancelButton = new javax.swing.JToggleButton();
        guestNameFld = new javax.swing.JTextField();
        choiceBox = new javax.swing.JComboBox<>();
        UsernameTxt3 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        amountField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        completeButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));

        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        UsernameTxt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt2.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt2.setText("Description");

        phoneField.setDisabledTextColor(java.awt.Color.black);
        phoneField.setEnabled(false);

        UsernameTxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt1.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt1.setText("Phone");

        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        UsernameTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt.setText("Guest Name");

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        guestNameFld.setDisabledTextColor(java.awt.Color.black);
        guestNameFld.setEnabled(false);

        choiceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Only Requested", "Only Confirmed", "All" }));
        choiceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBoxActionPerformed(evt);
            }
        });

        UsernameTxt3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameTxt3.setForeground(new java.awt.Color(215, 210, 203));
        UsernameTxt3.setText("Amount");

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(215, 210, 203));
        jLabel.setText("Choice");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        amountField.setDisabledTextColor(java.awt.Color.black);
        amountField.setEnabled(false);

        descriptionField.setDisabledTextColor(java.awt.Color.black);
        descriptionField.setEnabled(false);

        completeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        completeButton.setText("Complete");
        completeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(choiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(UsernameTxt2)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(UsernameTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descriptionField)
                            .addComponent(guestNameFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(UsernameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amountField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(UsernameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(confirmButton)
                        .addGap(95, 95, 95)
                        .addComponent(completeButton)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadServiceTable(String choice) {
        if (choice.equals("Only Requested")) {
            choice = "REQUESTED";
        } else if (choice.equals("Only Confirmed")) {
            choice = "CONFIRMED";
        }

        ServiceDAO serviceDAO = new ServiceDAO();
        List<Service> services = serviceDAO.getAllService(choice);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String[][] data = new String[services.size()][7];
        for (int i = 0; i < services.size(); i++) {
            data[i][0] = String.valueOf(services.get(i).getServiceID());
            data[i][1] = String.valueOf(services.get(i).getBookingID());
            data[i][2] = services.get(i).getDescription();
            data[i][3] = sdf.format(services.get(i).getIssueAt());
            data[i][4] = String.valueOf(services.get(i).getRoomNumber());
            data[i][5] = services.get(i).getServiceStatus().toString();
            data[i][6] = String.valueOf(services.get(i).getServiceAmount());
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "ServiceID", "Booking ID", "Description", "Issue At", "Room Number", "Service Status", "Service Amount"
                }
        ));        
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        // if userID starts with "G" then back to DashboardGuest, with "R" then back to DashboardReceptionist, with "M" then back to DashboardManager
        if (userID.startsWith("G")) {
            new DashboardGuest(userID).setVisible(true);
        } else if (userID.startsWith("R")) {
            try {
                new DashboardManager(userID).setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (userID.startsWith("M")) {
            try {
                new DashboardManager(userID).setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void choiceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBoxActionPerformed
        // TODO add your handling code here:
        loadServiceTable(choiceBox.getSelectedItem().toString());
    }//GEN-LAST:event_choiceBoxActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();

        String description = jTable2.getValueAt(row, 2).toString();
        double amount = Double.parseDouble(jTable2.getValueAt(row, 6).toString());

        descriptionField.setText(description);
        amountField.setText(String.valueOf(amount));

        String bookingID = jTable2.getValueAt(row, 1).toString();
        String guestID = new RoomBookingDAO().getGuestID(Integer.parseInt(bookingID));

        Person person = new PersonDAO().getPersonByID(guestID);
        guestNameFld.setText(person.getName());
        phoneField.setText(person.getPhone());
    }//GEN-LAST:event_jTable2MousePressed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a service to confirm", "Error", JOptionPane.ERROR_MESSAGE); 
            return;
        } else {
            String serviceStatus = jTable2.getValueAt(row, 5).toString();
            if (!serviceStatus.equals("REQUESTED") && !serviceStatus.equals("CANCELLED")) {
                JOptionPane.showMessageDialog(null, "Only REQUESTED or CANCELLED service can be confirmed", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int serviceID = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            ServiceDAO serviceDAO = new ServiceDAO();
            serviceDAO.updateServiceStatus(serviceID, ServiceStatus.CONFIRMED);
            JOptionPane.showMessageDialog(null, "Service confirmed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadServiceTable(choiceBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a service to cancel", "Error", JOptionPane.ERROR_MESSAGE); 
            return;
        } else {
            String serviceStatus = jTable2.getValueAt(row, 5).toString();
            if (!serviceStatus.equals("REQUESTED") && !serviceStatus.equals("CONFIRMED")) {
                JOptionPane.showMessageDialog(null, "Only REQUESTED or CONFIRMED service can be cancelled", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int serviceID = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            ServiceDAO serviceDAO = new ServiceDAO();
            serviceDAO.updateServiceStatus(serviceID, ServiceStatus.CANCELLED);
            JOptionPane.showMessageDialog(null, "Service cancelled successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadServiceTable(choiceBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void completeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a service to complete", "Error", JOptionPane.ERROR_MESSAGE); 
            return;
        } else {
            String serviceStatus = jTable2.getValueAt(row, 5).toString();
            if (!serviceStatus.equals("CONFIRMED")) {
                JOptionPane.showMessageDialog(null, "Only CONFIRMED service can be completed", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int serviceID = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            int bookingID = Integer.parseInt(jTable2.getValueAt(row, 1).toString());
            double serviceAmount = Double.parseDouble(jTable2.getValueAt(row, 6).toString());

            ServiceDAO serviceDAO = new ServiceDAO();
            serviceDAO.updateServiceStatus(serviceID, ServiceStatus.COMPLETED);


            Invoice invoice = new InvoiceDAO().getInvoiceByBookingID(bookingID);
            invoice.setTotalAmount(invoice.getTotalAmount() + serviceAmount);
            new InvoiceDAO().updateInvoice(invoice);


            JOptionPane.showMessageDialog(null, "Service completed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadServiceTable(choiceBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_completeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsernameTxt;
    private javax.swing.JLabel UsernameTxt1;
    private javax.swing.JLabel UsernameTxt2;
    private javax.swing.JLabel UsernameTxt3;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton backButton;
    private javax.swing.JToggleButton cancelButton;
    private javax.swing.JComboBox<String> choiceBox;
    private javax.swing.JToggleButton completeButton;
    private javax.swing.JToggleButton confirmButton;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JTextField guestNameFld;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField phoneField;
    // End of variables declaration//GEN-END:variables
}
