/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;

import com.rabbitmq.client.*;

import dao.NumberReadRequestDAO;
import dao.RequestDAO;

import javax.swing.*;



/**
 *
 * @author Thang
 */
public class DashboardReceptionist extends javax.swing.JFrame {
    
    private String userID;

    private Notification notification;

    private static final String EXCHANGE_NAME = "notifications";
    private Channel channel;

    private int numReadRequest = -1;
    private int maxRequest = -1;


    public DashboardReceptionist() {
        setTitle("Receptionist Dashboard");
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        initComponents();
        
        notification = new Notification();
        notification.setVisible(false);

        numReadRequest = new NumberReadRequestDAO().getNumberReadRequest(userID);
        System.out.println("numReadRequest: " + numReadRequest);
        maxRequest = new RequestDAO().getLastRequestID();
        System.out.println("maxRequest: " + maxRequest);

        if (maxRequest > numReadRequest) {
            notificationLabel.setVisible(true);
        } else {
            notificationLabel.setVisible(false);
        }

        add(notificationLabel, BorderLayout.SOUTH);

        try {
            setupRabbitMQ();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public DashboardReceptionist(String userID) {
        this.userID = userID;
        System.out.println("Receptionist Dashboard: " + userID);

        setTitle("Receptionist Dashboard");
        getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        initComponents();
        
        notification = new Notification();
        notification.setVisible(false);

        numReadRequest = new NumberReadRequestDAO().getNumberReadRequest(userID);
        System.out.println("numReadRequest: " + numReadRequest);
        maxRequest = new RequestDAO().getLastRequestID();
        System.out.println("maxRequest: " + maxRequest);

        if (maxRequest > numReadRequest) {
            notificationLabel.setVisible(true);
        } else {
            notificationLabel.setVisible(false);
        }

        add(notificationLabel, BorderLayout.SOUTH);

        try {
            setupRabbitMQ();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setupRabbitMQ() throws Exception {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("localhost");
        Connection connection = factory.newConnection();
        channel = connection.createChannel();
    
        channel.exchangeDeclare(EXCHANGE_NAME, "direct");
        String queueName = channel.queueDeclare().getQueue();
        channel.queueBind(queueName, EXCHANGE_NAME, "bookRoom");
        channel.queueBind(queueName, EXCHANGE_NAME, "callService");
    
        DeliverCallback deliverCallback = (consumerTag, delivery) -> {
            String message = new String(delivery.getBody(), "UTF-8");
    
            // Kiểm tra nếu thông báo là về việc đặt phòng hoặc gọi dịch vụ
            if (message.contains("bookRoom") || message.contains("callService")) {
                SwingUtilities.invokeLater(() -> {
                    notificationLabel.setVisible(true);
                });
            }
        };
        channel.basicConsume(queueName, true, deliverCallback, consumerTag -> { });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bookRoomButton = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        checkInButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        confirmBookButton = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        confirmServiceButton = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        notiButton = new javax.swing.JToggleButton();
        notificationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setPreferredSize(new java.awt.Dimension(1029, 502));

        logoutButton.setText("Log Out");
        logoutButton.setFocusable(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receptionistD.png"))); // NOI18N

        bookRoomButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotelBooking.png"))); // NOI18N
        bookRoomButton.setText("jButton1");
        bookRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomButtonActionPerformed(evt);
            }
        });

        jTextField6.setBackground(java.awt.Color.darkGray);
        jTextField6.setForeground(java.awt.Color.white);
        jTextField6.setText("Book Room");
        jTextField6.setBorder(null);

        checkInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_in.png"))); // NOI18N
        checkInButton.setText("jButton1");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        checkOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_out.png"))); // NOI18N
        checkOutButton.setText("jButton1");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        jTextField2.setBackground(java.awt.Color.darkGray);
        jTextField2.setForeground(java.awt.Color.white);
        jTextField2.setText("Check Out");
        jTextField2.setBorder(null);

        jTextField5.setBackground(java.awt.Color.darkGray);
        jTextField5.setForeground(java.awt.Color.white);
        jTextField5.setText("Check In");
        jTextField5.setBorder(null);

        confirmBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirmBook.jpg"))); // NOI18N
        confirmBookButton.setText("jButton1");
        confirmBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookButtonActionPerformed(evt);
            }
        });

        jTextField8.setBackground(java.awt.Color.darkGray);
        jTextField8.setForeground(java.awt.Color.white);
        jTextField8.setText("Confirm Book");
        jTextField8.setBorder(null);

        confirmServiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirmService.png"))); // NOI18N
        confirmServiceButton.setText("jButton1");
        confirmServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmServiceButtonActionPerformed(evt);
            }
        });

        jTextField9.setBackground(java.awt.Color.darkGray);
        jTextField9.setForeground(java.awt.Color.white);
        jTextField9.setText("Confirm Service");
        jTextField9.setBorder(null);

        notiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notiIcon (1).png"))); // NOI18N
        notiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiButtonActionPerformed(evt);
            }
        });

        notificationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pointRequest1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bookRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(notificationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notiButton)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notiButton)
                            .addComponent(notificationLabel))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bookRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(confirmBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(confirmServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int yesORno =
        JOptionPane.showConfirmDialog(
            null, "Are you sure ?", "Alert!", JOptionPane.YES_NO_OPTION);

        if (yesORno == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            System.out.println("Exited from DashBoard class");
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void bookRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BookRoom(userID).setVisible(true);
    }//GEN-LAST:event_bookRoomButtonActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CheckIn(userID).setVisible(true);
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CheckOut(userID).setVisible(true);
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void confirmBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ConfirmBook(userID).setVisible(true);
    }//GEN-LAST:event_confirmBookButtonActionPerformed

    private void confirmServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmServiceButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ConfirmService(userID).setVisible(true);
    }//GEN-LAST:event_confirmServiceButtonActionPerformed

    private void notiButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        numReadRequest = new NumberReadRequestDAO().getNumberReadRequest(userID);
        maxRequest = new RequestDAO().getLastRequestID();
        
        notificationLabel.setVisible(false);

        if(notification.isVisible()) {
            notification.setVisible(false);
        } else {
            java.awt.Point location = notiButton.getLocationOnScreen();
            notification.setLocation(location.x + notiButton.getWidth() - notification.getWidth(), location.y + notiButton.getHeight());
            
            // Gọi phương thức loadRequestTable
            int numHighlightedRows = maxRequest - numReadRequest;
            notification.loadRequestTable(numHighlightedRows);
            
            notification.setVisible(true);
        }
    
        new NumberReadRequestDAO().updateNumberReadRequest(userID, maxRequest);
        numReadRequest = maxRequest;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookRoomButton;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton confirmBookButton;
    private javax.swing.JButton confirmServiceButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton logoutButton;
    private javax.swing.JToggleButton notiButton;
    private javax.swing.JLabel notificationLabel;
    // End of variables declaration//GEN-END:variables
}
